/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=spikes/apple-publisher/https-auth/wrangler.jsonc --env=dev --include-runtime=false spikes/apple-publisher/https-auth/worker-configuration.d.ts` (hash: 5f15f20d754f2fa0da60df915656d346)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DEPLOYMENT_STAGE: "dev";
	PUBLIC_ORIGIN: "https://listen-cx-apple-auth-spike-dev.omar-alhait.workers.dev";
	DEVELOPER_TOKEN: string;
	INVITE_DIGEST: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
