/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=spikes/spotify-publisher/staging/wrangler.jsonc --env=staging --include-runtime=false spikes/spotify-publisher/staging/worker-configuration.d.ts` (hash: 0e6c0028d8ca9e32e6566b2a4b4ba098)
interface __BaseEnv_Env {
	DEPLOYMENT_STAGE: "staging";
	PUBLIC_ORIGIN: "https://listen-cx-spotify-spike-staging.omar-alhait.workers.dev";
	SPOTIFY_CLIENT_ID: string;
	OPERATOR_TOKEN: string;
	TOKEN_ENCRYPTION_KEY: string;
	SPOTIFY_STATE: DurableObjectNamespace<import("./worker").SpotifySpike>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "SpotifySpike";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOYMENT_STAGE" | "PUBLIC_ORIGIN" | "SPOTIFY_CLIENT_ID" | "OPERATOR_TOKEN" | "TOKEN_ENCRYPTION_KEY">> {}
}
